# 베이스 이미지로 Python 3.11 사용 (원하는 버전 가능)
FROM python:3.11-slim

# 작업 디렉토리 생성 및 설정
WORKDIR /sentiment

# requirements.txt 복사 및 의존성 설치
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cu118
# 앱 코드 복사
COPY ./app ./app

# FastAPI 실행 포트 설정
EXPOSE 8000

# 컨테이너 시작 시 uvicorn으로 FastAPI 실행
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
